/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentApproval: typeof import('./src/components/AgentApproval.vue')['default']
    AgentComposer: typeof import('./src/components/AgentComposer.vue')['default']
    AgentMessage: typeof import('./src/components/AgentMessage.vue')['default']
    AgentNotReady: typeof import('./src/components/AgentNotReady.vue')['default']
    AgentSessions: typeof import('./src/components/AgentSessions.vue')['default']
    AgentSuggestions: typeof import('./src/components/AgentSuggestions.vue')['default']
    AgentTyping: typeof import('./src/components/AgentTyping.vue')['default']
    AppCommandPalette: typeof import('./src/components/AppCommandPalette.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    CatalogCouponDialog: typeof import('./src/components/CatalogCouponDialog.vue')['default']
    CatalogImageInput: typeof import('./src/components/CatalogImageInput.vue')['default']
    CatalogImageListInput: typeof import('./src/components/CatalogImageListInput.vue')['default']
    CatalogItemPicker: typeof import('./src/components/CatalogItemPicker.vue')['default']
    CatalogListState: typeof import('./src/components/CatalogListState.vue')['default']
    CatalogOptionsEditor: typeof import('./src/components/CatalogOptionsEditor.vue')['default']
    CatalogPagination: typeof import('./src/components/CatalogPagination.vue')['default']
    CatalogProductHeader: typeof import('./src/components/CatalogProductHeader.vue')['default']
    CatalogProductSkeleton: typeof import('./src/components/CatalogProductSkeleton.vue')['default']
    CatalogRatingStars: typeof import('./src/components/CatalogRatingStars.vue')['default']
    CatalogSection: typeof import('./src/components/CatalogSection.vue')['default']
    CatalogStockControl: typeof import('./src/components/CatalogStockControl.vue')['default']
    CatalogVariantImageDialog: typeof import('./src/components/CatalogVariantImageDialog.vue')['default']
    CatalogVariantsPanel: typeof import('./src/components/CatalogVariantsPanel.vue')['default']
    CollectionDialog: typeof import('./src/components/CollectionDialog.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    CommandPaletteItem: typeof import('./src/components/CommandPaletteItem.vue')['default']
    FingerprintPanel: typeof import('./src/components/FingerprintPanel.vue')['default']
    FraudCustomerPanel: typeof import('./src/components/FraudCustomerPanel.vue')['default']
    FraudOrderPanel: typeof import('./src/components/FraudOrderPanel.vue')['default']
    FulfillmentPanel: typeof import('./src/components/FulfillmentPanel.vue')['default']
    FulfillmentShipDialog: typeof import('./src/components/FulfillmentShipDialog.vue')['default']
    FulfillmentStatusBadge: typeof import('./src/components/FulfillmentStatusBadge.vue')['default']
    JsonTree: typeof import('./src/components/JsonTree.vue')['default']
    OrderStatusBadge: typeof import('./src/components/OrderStatusBadge.vue')['default']
    RelatedOrdersPanel: typeof import('./src/components/RelatedOrdersPanel.vue')['default']
    ReturnRequestActions: typeof import('./src/components/ReturnRequestActions.vue')['default']
    ReturnsPanel: typeof import('./src/components/ReturnsPanel.vue')['default']
    ReturnStatusDialog: typeof import('./src/components/ReturnStatusDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupGuide: typeof import('./src/components/SetupGuide.vue')['default']
    SignalMatrix: typeof import('./src/components/SignalMatrix.vue')['default']
    StorefrontThemes: typeof import('./src/components/StorefrontThemes.vue')['default']
    UiDataTable: typeof import('./src/components/UiDataTable.vue')['default']
    UiEmptyState: typeof import('./src/components/UiEmptyState.vue')['default']
    UiFilterBar: typeof import('./src/components/UiFilterBar.vue')['default']
    UiPageHeader: typeof import('./src/components/UiPageHeader.vue')['default']
    UiPagination: typeof import('./src/components/UiPagination.vue')['default']
    UiSparkline: typeof import('./src/components/UiSparkline.vue')['default']
    UiStatTile: typeof import('./src/components/UiStatTile.vue')['default']
    UiStatusBadge: typeof import('./src/components/UiStatusBadge.vue')['default']
    WalkthroughCard: typeof import('./src/components/WalkthroughCard.vue')['default']
    WalkthroughGuide: typeof import('./src/components/WalkthroughGuide.vue')['default']
    WalkthroughText: typeof import('./src/components/WalkthroughText.vue')['default']
  }
}
